### ISSUE TITLE
Support Postgres

### ISSUE THREAD

**Issue by dalemccrory** [sixgweb/attributize-plugin-support#2]
Hello, we are using October CMS with Postgres. Would it be difficult to add support for Postgres? Thanks!

**Comment by sixgweb** [comment]
Hey Dale, I believe it should be pretty straightforward.  I'll add this to my queue and will get back to you on the progress.

**Comment by sixgweb** [comment]
Hi Dale, Postgres 12+ support added in [1.0.7 ](https://octobercms.com/plugin/sixgweb-attributize#changelog).

**Comment by dalemccrory** [comment]
Nice. Thank you so much!
